export const sampleData = {
  CODE: 200,
  CONTENTS: [
    {
      DOC_ID: "1237",
      NLP_DOC_ID: "결정문",
      NLP_RESULT: [
        {
          blockIndex: "0",
          displayName: "관할 법원",
          key: "1353",
          lineLoc: 3,
          pageId: 1,
          pageIndex: 0,
          showIdx: 2,
          value: "의정부지방법원 고양지원",
        },
        {
          blockIndex: "2",
          displayName: "사건번호",
          key: "1354",
          lineLoc: 5,
          pageId: 1,
          pageIndex: 0,
          showIdx: 4,
          value: "2022타기474",
        },
        {
          blockIndex: "2",
          displayName: "사건한글명",
          key: "1355",
          lineLoc: 5,
          pageId: 1,
          pageIndex: 0,
          showIdx: 4,
          value: "암류금지채권범위변경",
        },
        {
          blockIndex: "3",
          displayName: "채권자",
          key: "1356",
          lineLoc: 6,
          pageId: 1,
          pageIndex: 0,
          showIdx: 5,
          value: "김한진",
        },
        {
          blockIndex: "4",
          displayName: "채권자",
          key: "1356",
          lineLoc: 8,
          pageId: 1,
          pageIndex: 0,
          showIdx: 7,
          value: "주식회사 하나은행",
        },
        {
          blockIndex: "5",
          displayName: "제3채무자 당행 여부",
          key: "1360",
          lineLoc: 11,
          pageId: 1,
          pageIndex: 0,
          showIdx: 10,
          value: "Y",
        },
        {
          blockIndex: "6",
          displayName: "관련사건번호",
          key: "1374",
          lineLoc: 15,
          pageId: 1,
          pageIndex: 0,
          showIdx: 14,
          value: "2022타채50477",
        },
        {
          blockIndex: "6",
          displayName: "압류 문구 여부",
          key: "1361",
          lineLoc: 15,
          pageId: 1,
          pageIndex: 0,
          showIdx: 14,
          value: "Y",
        },
        {
          blockIndex: "6",
          displayName: "추심 문구 여부",
          key: "1372",
          lineLoc: 15,
          pageId: 1,
          pageIndex: 0,
          showIdx: 14,
          value: "Y",
        },
        {
          blockIndex: "7",
          displayName: "취소 문구 여부",
          key: "1366",
          lineLoc: 17,
          pageId: 1,
          pageIndex: 0,
          showIdx: 16,
          value: "Y",
        },
        {
          blockIndex: "8",
          displayName: "압류 문구 여부",
          key: "1361",
          lineLoc: 21,
          pageId: 1,
          pageIndex: 0,
          showIdx: 20,
          value: "Y",
        },
        {
          blockIndex: "8",
          displayName: "추심 문구 여부",
          key: "1372",
          lineLoc: 21,
          pageId: 1,
          pageIndex: 0,
          showIdx: 20,
          value: "Y",
        },
      ],
    },
  ],
  MESSAGE: "NLP Inference Process Complete",
  RCV_NO: "2023010314373101_01",
};
